name: Strings functions
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        ## continue-on-error: true
      - run: echo "${CONTEXT}"
        if: ${{ failure() }} # エラーが発生しても、failure関数があるので実行される
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'world') }} # フォーマット
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}  # カンマで結合
          CONTEXT: ${{ toJSON(github) }} # githubコンテキストをJSON文字列でダンプ
